version: "2"
plugins:
  codenarc:
    enabled: true
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig
  fixme:
    enabled: true
    config:
      strings:
      - TODO
      - FIXME
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
# https://docs.codeclimate.com/docs/advanced-configuration#section-exclude-patterns
exclude_patterns:
- "documentation/docs/images/*.png"
- "documentation/docs/images/*.ico"
- "cfg/id_rsa.enc"
