plugins:
  codenarc:
    enabled: true
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig
  fixme:
    enabled: true
    config:
      strings:
      - TODO
      - FIXME
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
