plugins:
  codenarc:
    enabled: true
  editorconfig:
    enabled: true
    checks:
      # https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013---line-length
      MD013:
        enabled: false
    config:
      editorconfig: .editorconfig
    # https://docs.codeclimate.com/docs/advanced-configuration#section-exclude-patterns
    exclude_patterns:
    - "documentation/docs/images/"
    - "cfg/id_rsa.enc"
  fixme:
    enabled: true
    config:
      strings:
      - TODO
      - FIXME
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
