plugins:
  codenarc:
    enabled: true
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig
    exclude_patterns:
    - "documentation/docs/images/"
    - "cfg/id_rsa.enc"
  fixme:
    enabled: true
    config:
      strings:
      - TODO
      - FIXME
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
# https://docs.codeclimate.com/docs/advanced-configuration#section-exclude-patterns
exclude_patterns:
- "test/resources/"
