version: "2"
checks:
  return-statements:
    enabled: false
plugins:
  codenarc:
    enabled: true
    checks:
      BooleanGetBoolean:
        enabled: false
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig
    # https://docs.codeclimate.com/docs/advanced-configuration#section-exclude-patterns
    exclude_patterns:
      - "documentation/**/images/"
      - "cfg/id_rsa.enc"
      - "**/testdata/**"
  fixme:
    enabled: true
    config:
      strings:
        - TODO
        - FIXME
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      # https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013---line-length
      MD013:
        enabled: false
      # https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md024
      MD024:
        enabled: false
      # https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md033---inline-html
      MD033:
        enabled: false
      # https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md036
      MD036:
        enabled: false
      # https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md041
      MD041:
        enabled: false
      # TODO: fix in separate PR
      # https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md004
      MD004:
        enabled: false
      # https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md040
      MD040:
        enabled: false
      # https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md046
      MD046:
        enabled: false
  shellcheck:
    enabled: true
exclude_patterns:
  - "**/*_generated.go"
  - "**/mocks/*.go"
  # default excludes are overwritten, add them again
  # https://docs.codeclimate.com/docs/excluding-files-and-folders#section-auto-generated-file-and-folder-exclusions
  - "**/*_test.go"
  - "**/test/"
