default: true

# ignore
MD013: false  # line-length
MD024: false  # no-duplicate-heading/no-duplicate-header
MD033: false  # no-inline-html
MD036: false  # no-emphasis-as-heading/no-emphasis-as-header
MD041: false  # first-line-heading/first-line-h1

# TODO: fix in separate PR
MD004: false  # ul-style
MD040: false  # fenced-code-language
MD046: false  # code-block-style
