quiet: false
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
outpkg: mocks
packages:
  github.com/SAP/jenkins-library/cmd:
    config:
      dir: cmd/mocks
    interfaces:
      GithubRepoClient:
  github.com/SAP/jenkins-library/pkg/config:
    config:
      dir: pkg/config/mocks
    interfaces:
      VaultClient:
  github.com/SAP/jenkins-library/pkg/jenkins:
    config:
      dir: pkg/jenkins/mocks
    interfaces:
      Artifact:
      Build:
      CredentialsManager:
      Jenkins:
      Job:
      Task:
  github.com/SAP/jenkins-library/pkg/kubernetes:
    config:
      dir: pkg/kubernetes/mocks
    interfaces:
      HelmExecutor:
  github.com/influxdata/influxdb-client-go/v2:
    config:
      dir: pkg/influx/mocks
    interfaces:
      Client:
  github.com/influxdata/influxdb-client-go/v2/api:
    config:
      dir: pkg/influx/mocks
    interfaces:
      WriteAPIBlocking:
