stages:
  Init:
    ordinal: 1

  'Initial Checks':
    ordinal: 10

  'Prepare System':
    ordinal: 20
    cfService: 'abap'
    cfServicePlan: 'standard'
    abapSystemIsDevelopmentAllowed: 'false'
    abapSystemSizeOfPersistence: 4
    abapSystemSizeOfRuntime: 1

  'Clone Repositories':
    ordinal: 30

  ATC:
    ordinal: 40

  Build:
    ordinal: 50

  'Integration Tests':
    ordinal: 60

  Confirm:
    ordinal: 70

  Publish:
    ordinal: 80

  Post:
    ordinal: 90
