Init:
  unstash: []
  stashes:
    - name: "source"
      includes: "**/*"
      excludes: ".pipeline/**"
'Prepare System':
  unstash:
  - source
  stashes: []
ATC:
  unstash:
  - source
  stashes: []
'Clone Repositories':
  unstash:
  - source
  stashes: []
Post:
  unstash: []
  stashes: []
