spec:
  stages:
    - displayName: Init
    - displayName: Initial Checks
    - displayName: Prepare System
    - displayName: AUnit
    - displayName: ATC
    - displayName: Clone Repositories
    - displayName: Build
    - displayName: Integration Tests
    - displayName: Confirm
    - displayName: Publish
    - displayName: Post
