# This file should be removed when existing cloud sdk consumers switched to general purpose pipeline
# This should be safe to do after Q2 2021

removedOrReplacedConfigKeys:
  extensionRepository:
    newConfigKey: "globalExtensionsRepository"
    general: true
    customMessage: "To configure a version please use globalExtensionsVersion.
      You can also configure globalExtensionsRepositoryCredentialsId in case the extension repository is secured.
      Please note that you can also configure these values as part of your custom defaults / shared configuration."
  orgToken:
    stages: ["whitesourceScan", "Security"]
    customMessage: "The credentials ID for the WhiteSource org-token should to be moved to the step configuration of 'whitesourceExecuteScan'.
      Store it as a 'Secret Text' in Jenkins and supply the ID the 'orgAdminUserTokenCredentialsId' field instead."
  archiveDebugLog:
    postAction: true
    customMessage: "Please use the step configuration for debugReportArchive instead."
  tmsUpload:
    stages: ["productionDeployment", "Release"]
    customMessage: "Please configure the step 'tmsUpload' instead.
      Details can be found in the release notes at https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v39 as well as in the step documentation: https://sap.github.io/jenkins-library/steps/tmsUpload/."
  sharedConfiguration:
    newConfigKey: "customDefaults"
    general: true
    customMessage: "In addition please move it to the root level of the config file, i.e. before the 'general' section.
      The value of this key needs to be a list of strings.
      See also https://sap.github.io/jenkins-library/configuration/#custom-default-configuration for more information.
      As an example for the necessary change, please consult the release notes of v33 of the Cloud SDK Pipeline at https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v33"
  automaticVersioning:
    general: true
    customMessage: "Please configure the 'artifactPrepareVersion' step instead.
      Details can be found in the release notes of v37 of the pipeline: https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v37"
  sapNpmRegistry:
    steps: ["executeNpm", "npmExecuteScripts", "npmExecuteLint", "mtaBuild"]
    warnInsteadOfError: true
    customMessage: "The parameter will be ignored during execution.
      This configuration option was removed in version v41, since the packages of the public SAP NPM Registry were migrated to the default public registry at npmjs.org.
      Please configure the defaultNpmRegistry parameter instead, in case a custom NPM registry configuration is required."
  sendNotification:
    postAction: true
    customMessage: "Details can be found in the release notes of v43 of the Cloud SDK Pipeline: https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v43"

requiredConfigKeys:
  inferBuildTool:
    general: true
    customMessage: "Please specify 'inferBuildTool: true' in the general section of your .pipeline/config.yml file.
        This will activate a number of features previously activated by the Cloud SDK Pipeline's default configuration."

removedOrReplacedSteps:
  executeMaven:
    newStepName: "mavenExecute"
  deployToCfWithCli:
    newStepName: "cloudFoundryDeploy"
  deployToNeoWithCli:
    newStepName: "deployToNeoWithCli"
  executeFortifyScan:
    newStepName: "fortifyExecuteScan"
  artifactSetVersion:
    newStepName: "artifactPrepareVersion"
    onlyCheckProjectConfig: true
    customMessage: "Details can be found in the release notes of v37 of the Cloud SDK Pipeline: https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v37"
  createHdiContainer:
    customMessage: "The createHdiContainer step is no longer available.
      If you still need the functionalities provided by this step, please open an issue at: https://github.com/SAP/cloud-s4-sdk-pipeline/issues/new?template=pipeline-issue.md
      Apart from that it is also possible to implement an extension for the stage 'Integration' using the extensibility concept explained in the documentation: https://sap.github.io/jenkins-library/extensibility/"
  checkJMeter:
    customMessage: "The checkJMeter step is no longer available.
      If you still need the functionalities provided by this step, please open an issue at: https://github.com/SAP/cloud-s4-sdk-pipeline/issues/new?template=pipeline-issue.md
      Apart from that it is also possible to implement an extension for the stage 'Performance' using the extensibility concept explained in the documentation: https://sap.github.io/jenkins-library/extensibility/"
  checkGatling:
    newStepName: "gatlingExecuteTests"

removedOrReplacedStages:
  integrationTests:
    newStageName: "Integration"
  backendIntegrationTests:
    newStageName: "Integration"
  frontendIntegrationTests:
    newStageName: "Integration"
  staticCodeChecks:
    customMessage: "Since version v32 of Cloud SDK Pipeline, it is required to migrate the configuration into your pom.xml file or to the configuration of the new step mavenExecuteStaticCodeChecks.
      Details can be found in the release notes as well as in the step documentation: https://sap.github.io/jenkins-library/steps/mavenExecuteStaticCodeChecks/."
  fortifyScan:
    customMessage: "To configure Fortify please use the step configuration for fortifyExecuteScan.
      Details can be found in the documentation: https://sap.github.io/jenkins-library/steps/fortifyExecuteScan/"
  lint:
    customMessage: "Since version v43 of Cloud SDK Pipeline, it is required to configure the step npmExecuteLint instead.
      Details can be found in the release notes as well as in the step documentation: https://sap.github.io/jenkins-library/steps/npmExecuteLint/."
  frontendUnitTests:
    newStageName: "Additional Unit Tests"
  npmAudit:
    customMessage: "Details can be found in the release notes of v43 of the Cloud SDK Pipeline: https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v43"
  s4SdkQualityChecks:
    customMessage: "Details can be found in the release notes of v43 of the Cloud SDK Pipeline: https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v43"
  sonarQubeScan:
    newStageName: "Compliance"
    customMessage: "Details can be found in the release notes of v43 of the Cloud SDK Pipeline: https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v43"
  checkmarxScan:
    newStageName: "Security"
    customMessage: "To configure Checkmarx please use the step configuration for checkmarxExecuteScan.
      Details can be found in the documentation: https://sap.github.io/jenkins-library/steps/checkmarxExecuteScan/"
  detectScan:
    newStageName: "Security"
    customMessage: "To configure Synopsys Detect please use the step configuration for detectExecuteScan.
      Details can be found in the documentation: https://sap.github.io/jenkins-library/steps/detectExecuteScan/"
  additionalTools:
    customMessage: "Details can be found in the release notes of v43 of the Cloud SDK Pipeline: https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v43"
  build:
    newStageName: "Build"
  integration:
    newStageName: "Integration"
  additionalUnitTests:
    newStageName: "Additional Unit Tests"
  endToEndTests:
    newStageName: "Acceptance"
  performanceTests:
    newStageName: "Performance"
  security:
    newStageName: "Security"
  compliance:
    newStageName: "Compliance"
  artifactDeployment:
    customMessage: "The General Purpose Pipeline does not execute the stage 'Artifact Deployment' and there is no alternative stage for the functionality."
  productionDeployment:
    newStageName: "Release"

parameterTypeChanged:
  appUrls:
    oldType: "String"
    newType: "List"
    stages: ["productionDeployment", "endToEndTests", "Release", "Acceptance"]

renamedNpmScript:
  ci-integration-test:
    newScriptName: "ci-it-backend"
  ci-test:
    newScriptName: "ci-frontend-unit-test"
    warnInsteadOfError: true
