stages:
  build:
    stepConditions:
      mavenExecuteStaticCodeChecks:
        filePattern: 'pom.xml'
      npmExecuteLint:
        filePattern:
          - '**/*.js'
          - '**/*.jsx'
          - '**/*.ts'
          - '**/*.tsx'
  backendIntegrationTests:
    stepConditions:
      npmExecuteScripts:
        npmScripts:
          - 'ci-it-backend'
      mavenExecuteIntegration:
        filePattern: 'integration-tests/pom.xml'
  compliance:
    onlyProductiveBranch: true
    stepConditions:
      sonarExecuteScan:
        configKeys:
          - 'sonarTokenCredentialsId'
          - 'projectKey'
          - 'instance'
  frontendIntegrationTests:
    stepConditions:
      npmExecuteScripts:
        npmScripts:
          - 'ci-it-frontend'
  additionalUnitTests:
    stepConditions:
      npmExecuteScripts:
        npmScripts:
          - 'ci-frontend-unit-test'
  endToEndTests:
    stepConditions:
      multicloudDeploy:
        configKeys:
          - 'cfTargets'
          - 'neoTargets'
      cloudFoundryDeploy:
        configKeys:
          - 'cfSpace'
          - 'cloudFoundry/space'
      healthExecuteCheck:
        configKeys:
          - 'testServerUrl'
      newmanExecute:
        filePatternFromConfig: 'newmanCollection'
        configKeys:
          - 'testRepository'
      uiVeri5ExecuteTests:
        filePattern: '**/conf.js'
        configKeys:
          - 'testRepository'
      npmExecuteEndToEndTests:
        configKeys:
          - 'appUrls'
  performanceTests:
    stepConditions:
      performanceTests:
        configKeys:
          - 'cfTargets'
          - 'neoTargets'
  security:
    onlyProductiveBranch: true
    stepConditions:
      checkmarxExecuteScan:
        configKeys:
          - 'groupId'
      detectExecuteScan:
        configKeys:
          - 'detectTokenCredentialsId'
      fortifyExecuteScan:
        configKeys:
          - 'fortifyCredentialsId'
      whitesourceExecuteScan:
        configKeys:
          - 'productName'
          - 'orgAdminUserTokenCredentialsId'
          - 'userTokenCredentialsId'
  productionDeployment:
    onlyProductiveBranch: true
    stepConditions:
      multicloudDeploy:
        configKeys:
          - 'cfTargets'
          - 'neoTargets'
      cloudFoundryDeploy:
        configKeys:
          - 'cfSpace'
          - 'cloudFoundry/space'
      neoDeploy:
        configKeys:
          - 'neo/account'
      tmsUpload:
        configKeys:
          - 'credentialsId'
          - 'mtaPath'
          - 'nodeName'
      healthExecuteCheck:
        configKeys:
          - 'testServerUrl'
      npmExecuteEndToEndTests:
        configKeys:
          - 'appUrls'
      githubPublishRelease:
        configKeys:
          - 'githubTokenCredentialsId'
  artifactDeployment:
    onlyProductiveBranch: true
    stepConditions:
      artifactDeployment:
        configKeys:
          - 'nexus'
  postPipelineHook:
    stepConditions:
      postPipelineHook:
        configKeys:
          - 'enabled'
  archiveReport:
    stepConditions:
      archiveReport:
        filePattern:
          - 'mta.yaml'
          - 'pom.xml'
