removedOrReplacedConfigKeys:
  extensionRepository:
    newConfigKey: "globalExtensionsRepository"
    general: true
    customMessage: "To configure a version please use globalExtensionsVersion.
      You can also configure globalExtensionsRepositoryCredentialsId in case the extension repository is secured.
      Please note that you can also configure these values as part of your custom defaults / shared configuration."
  globalSettingsFile:
    steps: ["mavenExecute"]
    customMessage: "The SAP Cloud SDK Pipeline uses an own global settings file to inject its download proxy as maven repository mirror.
      Please only specify the settings via the parameter 'projectSettingsFile'"
  orgToken:
    newConfigKey: "credentialsId"
    stages: ["whitesourceScan"]
    customMessage: "Store it as a 'Secret Text' in Jenkins and use the 'credentialsId' field instead."
  archiveDebugLog:
    postAction: true
    customMessage: "Please use the step configuration for debugReportArchive instead."
  tmsUpload:
    stages: ["productionDeployment"]
    customMessage: "Since version v39 it is required to configure the step tmsUpload instead.
      Details can be found in the release notes at https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v39 as well as in the step documentation: https://sap.github.io/jenkins-library/steps/tmsUpload/."
  sharedConfiguration:
    newConfigKey: "customDefaults"
    general: true
    customMessage: "In addition please move it to the root level of the config file, i.e. before the 'general' section.
      The value of this key needs to be a list of strings.
      See also https://sap.github.io/jenkins-library/configuration/#custom-default-configuration for more information.
      As an example for the necessary change, please consult the release notes of v33 at https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v33"
  automaticVersioning:
    general: true
    customMessage: "Please configure the artifactPrepareVersion step instead.
      Details can be found in the release notes of v37 of the pipeline: https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v37"
  sapNpmRegistry:
    steps: ["executeNpm", "npmExecuteScripts", "npmExecuteLint", "mtaBuild"]
    warnInsteadOfError: true
    customMessage: "The parameter will be ignored during execution.
      This configuration option was removed in version v41, since the packages of the public SAP NPM Registry were migrated to the default public registry at npmjs.org.
      Please configure the defaultNpmRegistry parameter instead, in case a custom NPM registry configuration is required."
  sendNotification:
    postAction: true
    customMessage: "Details can be found in the release notes of v43 of the pipeline: https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v43"

removedOrReplacedSteps:
  executeMaven:
    newStepName: "mavenExecute"
  deployToCfWithCli:
    newStepName: "cloudFoundryDeploy"
  deployToNeoWithCli:
    newStepName: "deployToNeoWithCli"
  executeFortifyScan:
    newStepName: "fortifyExecuteScan"
  artifactSetVersion:
    newStepName: "artifactPrepareVersion"
    onlyCheckProjectConfig: true
    customMessage: "Details can be found in the release notes of v37 of the pipeline: https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v37"
  createHdiContainer:
    customMessage: "The backendIntegrationTests stage has been aligned with project 'Piper' in version v41 and activation of the createHdiContainer step was not migrated.
      If you still need the functionalities provided by the createHdiContainer step, please open an issue at: https://github.com/SAP/cloud-s4-sdk-pipeline/issues/new?template=pipeline-issue.md
      Apart from that it is also possible to implement an extension for the backendIntegrationTests stage using the extensibility concept explained in the documentation: https://sap.github.io/jenkins-library/extensibility/
      For the time being, the step createHdiContainer is still available in the Pipeline and can be called from an extension.
      The extension must pass all required options to the step via parameters, it cannot be configured in your .pipeline/config.yml."

removedOrReplacedStages:
  integrationTests:
    newStageName: "integration"
  backendIntegrationTests:
    newStageName: "integration"
  frontendIntegrationTests:
    newStageName: "integration"
  staticCodeChecks:
    customMessage: "Since version v32 it is required to migrate the configuration into your pom.xml file or to the configuration of the new step mavenExecuteStaticCodeChecks.
      Details can be found in the release notes as well as in the step documentation: https://sap.github.io/jenkins-library/steps/mavenExecuteStaticCodeChecks/."
  fortifyScan:
    customMessage: "To configure fortify please use the step configuration for fortifyExecuteScan.
      Details can be found in the documentation: https://sap.github.io/jenkins-library/steps/fortifyExecuteScan/"
  lint:
    customMessage: "Since version v43 it is required to configure the step npmExecuteLint instead.
      Details can be found in the release notes as well as in the step documentation: https://sap.github.io/jenkins-library/steps/npmExecuteLint/."
  frontendUnitTests:
    newStageName: "additionalUnitTests"
  npmAudit:
    customMessage: "Details can be found in the release notes of v43 of the pipeline: https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v43"
  s4SdkQualityChecks:
    customMessage: "Details can be found in the release notes of v43 of the pipeline: https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v43"
  sonarQubeScan:
    newStageName: "compliance"
    customMessage: "Details can be found in the release notes of v43 of the pipeline: https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v43"
  checkmarxScan:
    newStageName: "security"
    customMessage: "To configure Checkmarx please use the step configuration for checkmarxExecuteScan.
      Details can be found in the documentation: https://sap.github.io/jenkins-library/steps/checkmarxExecuteScan/"
  detectScan:
    newStageName: "security"
    customMessage: "To configure Synopsys Detect please use the step configuration for detectExecuteScan.
      Details can be found in the documentation: https://sap.github.io/jenkins-library/steps/detectExecuteScan/"
  additionalTools:
    customMessage: "Details can be found in the release notes of v43 of the pipeline: https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v43"

parameterTypeChanged:
  appUrls:
    oldType: "String"
    newType: "List"
    stages: ["productionDeployment", "endToEndTests"]

renamedNpmScript:
  ci-integration-test:
    newScriptName: "ci-it-backend"
  ci-test:
    newScriptName: "ci-frontend-unit-test"
    warnInsteadOfError: true
