stages:
  Init:
    stepConditions:
      slackSendNotification:
        config: 'channel'
  'Pull-Request Voting': {}
  Build: {}
  'Additional Unit Tests': {}
  Integration: {}
  Acceptance:
    stepConditions:
      cloudFoundryDeploy:
        config: 'cfSpace'
      newmanExecute:
        filePatternFromConfig: 'newmanCollection'
        config: 'testRepository'
      uiVeri5ExecuteTests:
        filePattern: '**/conf.js'
        config: 'testRepository'
  Security: {}
  Performance: {}
  Compliance: {}
  Promote: {}
  Release: {}
  'Post Actions':
    stepConditions:
      slackSendNotification:
        config: 'channel'
