// +build !release
// Code generated by mockery v2.0.3. DO NOT EDIT.

package mocks

import (
	api "github.com/hashicorp/vault/api"
	mock "github.com/stretchr/testify/mock"
)

// VaultMock is an autogenerated mock type for the logicalClient type
type VaultMock struct {
	mock.Mock
}

// Read provides a mock function with given fields: _a0
func (_m *VaultMock) Read(_a0 string) (*api.Secret, error) {
	ret := _m.Called(_a0)

	var r0 *api.Secret
	if rf, ok := ret.Get(0).(func(string) *api.Secret); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
