apiVersion: apps/v1
kind: Deployment
metadata:
  name: myFancyApp
  labels:
    tier: application
spec:
  replicas: 4
  selector:
    matchLabels:
      run: myContainer
  template:
    metadata:
      labels:
        run: myContainer
    spec:
      containers:
      - image: myregistry.com/myFancyContainer:1336
        name: myContainer