metadata:
    name: abapEnvironmentCheckoutBranch
    description: TEST
    longDescription: Checkout branch TBD
spec:
    inputs:
      secrets:
        - name: abapCredentialsId
          description: Jenkins credentials ID containing user and password to authenticate to the Cloud Platform ABAP Environment system or the Cloud Foundry API
          type: jenkins
          aliases:
            - name: cfCredentialsId
            - name: credentialsId
      params:
        - name: username
          type: string
          description: User for either the Cloud Foundry API or the Communication Arrangement for SAP_COM_0510
          scope:
          - PARAMETERS
          - STAGES
          - STEPS
          mandatory: true
          secret: true
        - name: password
          type: string
          description: Password for either the Cloud Foundry API or the Communication Arrangement for SAP_COM_0510
          scope:
          - PARAMETERS
          - STAGES
          - STEPS
          mandatory: true
          secret: true
        - name: repositoryName
          type: string
          description: Specifies a Repository (Software Component) on the SAP Cloud Platform ABAP Environment system
          scope:
          - PARAMETERS
          - STAGES
          - STEPS
          mandatory: true
        - name: branchName
          type: string
          description: Specifies a Branch of a Repository (Software Component) on the SAP Cloud Platform ABAP Environment system
          scope:
          - PARAMETERS
          - STAGES
          - STEPS
          mandatory: true
        - name: host
          type: string
          description: Specifies the host address of the SAP Cloud Platform ABAP Environment system
          scope:
          - PARAMETERS
          - STAGES
          - STEPS
        - name: cfApiEndpoint
          type: string
          description: Cloud Foundry API Enpoint
          scope:
          - PARAMETERS
          - STAGES
          - STEPS
          - GENERAL
          aliases:
            - name: cloudFoundry/apiEndpoint
        - name: cfOrg
          type: string
          description: Cloud Foundry target organization
          scope:
          - PARAMETERS
          - STAGES
          - STEPS
          - GENERAL
          aliases:
            - name: cloudFoundry/org
        - name: cfSpace
          type: string
          description: Cloud Foundry target space
          scope:
          - PARAMETERS
          - STAGES
          - STEPS
          - GENERAL
          aliases:
            - name: cloudFoundry/space
        - name: cfServiceInstance
          type: string
          description: Cloud Foundry Service Instance
          scope:
          - PARAMETERS
          - STAGES
          - STEPS
          - GENERAL
          aliases:
            - name: cloudFoundry/serviceInstance
        - name: cfServiceKey
          type: string
          description: Cloud Foundry Service Key
          scope:
          - PARAMETERS
          - STAGES
          - STEPS
          - GENERAL
          aliases:
            - name: cloudFoundry/serviceKey
            - name: cloudFoundry/serviceKeyName
            - name: cfServiceKeyName
    containers:
      - name: cf
        image: ppiper/cf-cli
        imagePullPolicy: Never
  