name: "Documentation"

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: 'Format'
    steps:
    - uses: actions/checkout@v2
    - name: Lint Code Base
      uses: github/super-linter@v2.0.0
