name: Build and Release master branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - env:
          CGO_ENABLED: 0
        run: |
          export GIT_COMMIT=$(git rev-parse HEAD) && \
          export GIT_REPOSITORY=$(git config --get remote.origin.url) && \
          go build -ldflags "-X github.com/SAP/jenkins-library/cmd.GitCommit=${GIT_COMMIT} \
                  -X github.com/SAP/jenkins-library/pkg/log.LibraryRepository=${GIT_REPOSITORY} \
                  -X github.com/SAP/jenkins-library/pkg/telemetry.LibraryRepository=${GIT_REPOSITORY}" \
            -o piper_master .
        shell: bash
      - run: ./piper_master version
        shell: bash
      - uses: actions/upload-artifact@v1
        with:
          name: piper_master
          path: piper_master
      - uses: SAP/project-piper-action@master
        with:
         command: githubPublishRelease
         flags: --verbose --token ${{ secrets.GITHUB_TOKEN }} --owner fwilhe --version latest --assetPath ./piper_master
