name: Go1

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  unit:

    if: |
      (
        github.event.comment.body == '/ut' ||
        github.event.comment.body == '/ut-go'
      ) && (
        github.event.comment.author_association == 'COLLABORATOR' ||
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER'
      )

    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
      - uses: actions/setup-go@v1
        with:
          go-version: '1.18.x'
      - name: Cache Golang Packages
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: checkout
        uses: actions/checkout@v2
      - name: unit-test
        run: echo ${{secrets.ENV_TEST}}
