name: CI

on: [push]

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.x'

    - name: checkout
      uses: actions/checkout@v2

    - name: generate
      run: go run pkg/generator/step-metadata.go

    - name: format
      run: go fmt

    - name: cleanup dependencies
      run: go mod tidy
        
    - name: dummy change
      run: echo tests >> Dockerfile

    - name: verify
      run: git diff --name-only --exit-code
